import React, { useState, useEffect } from 'react';
import * as reportService from '../services/reportService';
import Button from '../components/common/Button';
import Card from '../components/common/Card';
import Loader from '../components/common/Loader';
import EmptyState from '../components/common/EmptyState';
import Table from '../components/common/Table';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await reportService.getReports();
      setReports(Array.isArray(data) ? data : data.reports || []);
    } catch (err) {
      setError(err.message || 'Failed to load reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleDownload = async (reportId, format) => {
    try {
      const blob = await reportService.downloadReport(reportId, format);
      const url = window.URL.createObjectURL(new Blob([blob]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `report-${reportId}.${format}`);
      document.body.appendChild(link);
      link.click();
      link.parentNode.removeChild(link);
    } catch (err) {
      alert('Failed to download report file.');
    }
  };

  const headers = ['Report Name', 'Type', 'Generated Date', 'Actions'];

  const renderRow = (report) => (
    <tr key={report.id}>
      <td>{report.name || 'Unnamed Report'}</td>
      <td>{report.type || 'Summary'}</td>
      <td>{report.createdAt ? new Date(report.createdAt).toLocaleDateString() : 'N/A'}</td>
      <td>
        <div className="flex gap-2">
          <Button onClick={() => handleDownload(report.id, 'csv')} className="btn-secondary">
            CSV
          </Button>
          <Button onClick={() => handleDownload(report.id, 'pdf')} className="btn-secondary">
            PDF
          </Button>
        </div>
      </td>
    </tr>
  );

  return (
    <div className="reports-page container">
      <div className="flex justify-between items-center mb-6">
        <h1>Reports & Audits</h1>
        <Button onClick={fetchReports} className="btn-secondary">
          Refresh List
        </Button>
      </div>

      {error && <div className="alert alert-danger">{error}</div>}

      {loading ? (
        <Loader text="Fetching reports list..." />
      ) : reports.length === 0 ? (
        <EmptyState
          message="No reports generated yet"
          description="Reports generated by audit tasks or system managers will appear here."
        />
      ) : (
        <Card>
          <Table headers={headers} data={reports} renderRow={renderRow} />
        </Card>
      )}
    </div>
  );
};

export default Reports;
